### ISSUE TITLE
Points disappearing if coordinate placed before resource

### ISSUE THREAD

**Issue by itspangler** [allmaps/editor#52]
I just started seeing a bug where coordinate points disappear if you place them before image/resource points., e.g., in the GIF below, I place geographic coordinate #6 before placing pixel coordinate #6, and it disappears, throwing variations of this error:
```
Uncaught Error: Cannot read properties of undefined (reading '0')
    at v (connection.js:264:13)
    at g.handleMessage (connection.js:192:11)
    at e.onmessage (connection.js:143:18)
    at WebSocket._handleMessage (reconnecting-websocket-mjs.js:172:23)
```

![Recording 2024-04-10 at 11 04 55](https://github.com/allmaps/editor/assets/39773984/3220a0ef-7ac3-468e-95de-d808af23c172)

**Comment by bertspaan** [comment]
What's the URL of the IIIF resource where this is happening?

**Comment by itspangler** [comment]
Here's the manifest where I first noticed it: https://www.digitalcommonwealth.org/search/commonwealth:7s75h3704/manifest

As far as I can tell, though, it's happening globally; here's a few other maps where I tested it and experienced the same behavior:
- [Library of Congress](https://www.loc.gov/item/91685161/manifest.json)
- [LMEC](https://collections.leventhalmap.org/search/commonwealth:6q185466n)
- [Rumsey](https://www.davidrumsey.com/luna/servlet/iiif/m/RUMSEY~8~1~31698~1150493/manifest)
